Create namespace when it does not exist
aws/aws-cloud-map-mcs-controller-for-k8s pull request #25
Opened 2021-10-09 03:07 UTC by thalleslmF

Signed-off-by: thalles <thalles.freitas@zup.com.br>

*Issue #, if available:*
#19 
*Description of changes:*
Now create namespace if does not exist on cloudmap when creating a service

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-10-11 23:52 UTC, vanekjar requested changes
Thank you for your contribution. Adding few comments how to make the code robust.

2021-10-14 22:29 UTC, vanekjar requested changes

2021-10-14 23:50 UTC, astaticvoid requested changes

2021-10-15 00:15 UTC, astaticvoid commented
Looks good to me, signing off on my end.
Thanks for the improvements and being the project's first public contributor!
I will have to make some modifications when I rebase my latest [pull request to modularize the client and modify polling logic](https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s/pull/31), but the implementation is good.

2021-10-15 00:17 UTC, astaticvoid approved these changes

2021-10-15 01:35 UTC, vanekjar approved these changes
Thanks for the contribution!

2021-10-15 05:15 UTC, merged